//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryYellowBall
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int BookingId { get; set; }
        public int CustId { get; set; }
        public Nullable<int> TrainerId { get; set; }
        public int CourtId { get; set; }
        public decimal PayAmount { get; set; }
        public System.DateTime BookDate { get; set; }
        public System.DateTime Date { get; set; }
        public string SessionTime { get; set; }
        public Nullable<bool> Equipment { get; set; }
    
        public virtual Court Court { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Trainer Trainer { get; set; }
    }
}
